# Generated by Django 6.0.7 on 2026-07-16 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200, unique=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='프리셋명')),
                ('is_default', models.BooleanField(default=False, verbose_name='기본 프리셋')),
                ('ki_min', models.IntegerField(blank=True, null=True, verbose_name='KI 최소')),
                ('ki_max', models.IntegerField(blank=True, null=True, verbose_name='KI 최대')),
                ('include_no_ki', models.BooleanField(default=True, verbose_name='NoKI 포함')),
                ('asset_type', models.CharField(choices=[('전체', '전체'), ('지수형', '지수형'), ('종목형', '종목형')], default='전체', max_length=5, verbose_name='자산유형')),
                ('yield_min', models.FloatField(blank=True, null=True, verbose_name='최소 수익률(%)')),
                ('period_max', models.IntegerField(blank=True, null=True, verbose_name='최대 주기(개월)')),
                ('currency', models.CharField(choices=[('전체', '전체'), ('KRW', 'KRW'), ('USD', 'USD')], default='전체', max_length=5, verbose_name='통화')),
                ('notify', models.BooleanField(default=True, verbose_name='텔레그램 알림')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=50, verbose_name='발행사')),
                ('product_no', models.CharField(blank=True, max_length=30, verbose_name='상품번호')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='상품명')),
                ('product_type', models.CharField(choices=[('ELS', 'ELS'), ('DLS', 'DLS'), ('ELB', 'ELB'), ('DLB', 'DLB')], default='ELS', max_length=5, verbose_name='상품유형')),
                ('yield_rate', models.FloatField(blank=True, null=True, verbose_name='연수익률(%)')),
                ('max_loss', models.FloatField(blank=True, null=True, verbose_name='최대손실률(%)')),
                ('ki', models.IntegerField(blank=True, null=True, verbose_name='KI배리어(%)')),
                ('is_no_ki', models.BooleanField(default=False, verbose_name='NoKI 여부')),
                ('barrier_first', models.IntegerField(blank=True, null=True, verbose_name='1차 조기상환(%)')),
                ('barrier_last', models.IntegerField(blank=True, null=True, verbose_name='마지막 조기상환(%)')),
                ('barriers_raw', models.JSONField(blank=True, null=True, verbose_name='배리어 전체')),
                ('period_months', models.IntegerField(blank=True, null=True, verbose_name='조기상환주기(개월)')),
                ('asset_type', models.CharField(blank=True, choices=[('지수형', '지수형'), ('종목형', '종목형')], max_length=5, verbose_name='기초자산유형')),
                ('assets_raw', models.CharField(blank=True, max_length=200, verbose_name='기초자산')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='발행일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만기일')),
                ('sub_start', models.DateField(blank=True, null=True, verbose_name='청약시작일')),
                ('sub_end', models.DateField(blank=True, null=True, verbose_name='청약마감일')),
                ('currency', models.CharField(default='KRW', max_length=5, verbose_name='통화')),
                ('description', models.TextField(blank=True, verbose_name='상품설명 원문')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'ordering': ['sub_end', '-yield_rate'],
                'constraints': [models.UniqueConstraint(fields=('issuer', 'product_no', 'sub_end'), name='uniq_product')],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(verbose_name='투자금액(원)')),
                ('invested_at', models.DateField(verbose_name='청약일')),
                ('broker_account', models.CharField(blank=True, max_length=100, verbose_name='증권사/계좌 메모')),
                ('status', models.CharField(choices=[('보유중', '보유중'), ('조기상환', '조기상환'), ('만기상환', '만기상환'), ('낙인후상환', '낙인후상환')], default='보유중', max_length=10, verbose_name='상태')),
                ('redeemed_at', models.DateField(blank=True, null=True, verbose_name='상환일')),
                ('redeemed_amount', models.BigIntegerField(blank=True, null=True, verbose_name='상환금액(원)')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotifiedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.preset')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('preset', 'product'), name='uniq_notified')],
            },
        ),
        migrations.CreateModel(
            name='RedemptionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(verbose_name='회차')),
                ('alert_type', models.CharField(max_length=5)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investment', 'round_no', 'alert_type'), name='uniq_redemption_alert')],
            },
        ),
    ]
