# Generated by Django 6.0.7 on 2026-07-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockInAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_band', models.CharField(max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investment', 'level_band'), name='uniq_ki_alert')],
            },
        ),
        migrations.CreateModel(
            name='KnockInStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('ref_price', models.FloatField(blank=True, null=True, verbose_name='발행일 기준가')),
                ('current_price', models.FloatField(blank=True, null=True, verbose_name='현재가')),
                ('level_pct', models.FloatField(blank=True, null=True, verbose_name='현재 레벨(%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ki_status', to='core.investment')),
            ],
            options={
                'ordering': ['level_pct'],
                'constraints': [models.UniqueConstraint(fields=('investment', 'asset_name'), name='uniq_ki_status')],
            },
        ),
    ]
