# Generated by Django 6.0.7 on 2026-07-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_knockinalert_knockinstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='issuer',
            field=models.CharField(blank=True, max_length=50, verbose_name='발행사'),
        ),
    ]
