# Generated by Django 6.0.7 on 2026-07-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_preset_issuer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preset',
            name='issuer',
        ),
        migrations.AddField(
            model_name='preset',
            name='issuers',
            field=models.JSONField(blank=True, default=list, verbose_name='발행사 목록'),
        ),
    ]
