# Generated by Django 6.0.7 on 2026-07-18 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_preset_issuer_preset_issuers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='상품코드'),
        ),
    ]
