# Generated by Django 6.0.7 on 2026-07-19 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_first_eval_months_product_schedule_estimated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedemptionVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField(verbose_name='회차')),
                ('eval_date', models.DateField(verbose_name='평가일')),
                ('barrier', models.FloatField(blank=True, null=True, verbose_name='배리어(%)')),
                ('worst_level', models.FloatField(blank=True, null=True, verbose_name='워스트 레벨(%)')),
                ('worst_asset', models.CharField(blank=True, max_length=50)),
                ('met', models.BooleanField(null=True, verbose_name='충족 여부')),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='core.investment')),
            ],
            options={
                'ordering': ['-eval_date'],
                'constraints': [models.UniqueConstraint(fields=('investment', 'round_no'), name='uniq_redemption_verdict')],
            },
        ),
    ]
