# Generated by Django 6.0.7 on 2026-07-20 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_redemptionverdict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='watchitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='watchitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch', to='core.product'),
        ),
        migrations.AddConstraint(
            model_name='watchitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='uniq_watch_user_product'),
        ),
    ]
