# Generated by Django 6.0.7 on 2026-07-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_preset_user_watchitem_user_alter_watchitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ISIN')),
                ('shotn_isin', models.CharField(blank=True, max_length=15, verbose_name='단축코드')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='종목명')),
                ('issuer', models.CharField(db_index=True, max_length=50, verbose_name='발행사')),
                ('product_type', models.CharField(max_length=5, verbose_name='상품유형')),
                ('recu_whcd', models.CharField(blank=True, max_length=10, verbose_name='발행구분')),
                ('currency_name', models.CharField(blank=True, max_length=10, verbose_name='통화')),
                ('issue_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='발행일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만기일')),
                ('basset_sort', models.CharField(blank=True, max_length=20, verbose_name='기초자산유형')),
                ('basset_count', models.IntegerField(blank=True, null=True, verbose_name='기초자산개수')),
                ('assets', models.JSONField(blank=True, default=list, verbose_name='기초자산 목록')),
                ('issue_amount', models.BigIntegerField(blank=True, null=True, verbose_name='발행금액')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
