# Generated by Django 6.0.7 on 2026-07-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_historicalissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isin', models.CharField(db_index=True, max_length=20, verbose_name='ISIN')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='종목명')),
                ('issuer', models.CharField(db_index=True, max_length=50, verbose_name='발행사')),
                ('product_type', models.CharField(blank=True, max_length=5, verbose_name='상품유형')),
                ('recu_whcd', models.CharField(blank=True, max_length=10, verbose_name='발행구분')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='발행일')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='만기일')),
                ('redemption_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='상환일')),
                ('exercise_type', models.CharField(blank=True, max_length=10, verbose_name='상환유형')),
                ('planned_term_months', models.IntegerField(blank=True, null=True, verbose_name='예정만기(개월)')),
                ('held_months', models.IntegerField(blank=True, null=True, verbose_name='실제보유(개월)')),
                ('asset_type_name', models.CharField(blank=True, max_length=20, verbose_name='기초자산유형')),
                ('basset_count', models.IntegerField(blank=True, null=True, verbose_name='기초자산개수')),
                ('assets', models.JSONField(blank=True, default=list, verbose_name='기초자산명 목록')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'ordering': ['-redemption_date'],
                'constraints': [models.UniqueConstraint(fields=('isin', 'redemption_date'), name='uniq_redemption_isin_date')],
            },
        ),
    ]
