# Generated by Django 6.0.7 on 2026-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historicalredemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalYieldStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='연도')),
                ('basset_sort', models.CharField(blank=True, max_length=20, verbose_name='기초자산유형')),
                ('assets', models.JSONField(blank=True, default=list, verbose_name='기초자산 조합')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='상환건수(CNT_HAP)')),
                ('redemption_amount', models.BigIntegerField(blank=True, null=True, verbose_name='상환금액합계(REDAMT_VAL_HAP)')),
                ('margin_rate', models.FloatField(blank=True, null=True, verbose_name='실현수익률(%, RED_MARGIN_RATE)')),
                ('planned_months', models.IntegerField(blank=True, null=True, verbose_name='평균예정만기(개월)')),
                ('held_months', models.IntegerField(blank=True, null=True, verbose_name='평균실제보유(개월)')),
                ('minus_count', models.IntegerField(blank=True, null=True, verbose_name='손실건수(MINUS_CNT)')),
                ('minus_amount', models.BigIntegerField(blank=True, null=True, verbose_name='손실금액(MINUS_RED_AMT)')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
            ],
            options={
                'ordering': ['-year', '-count'],
            },
        ),
    ]
