# Generated by Django 6.0.7 on 2026-07-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_historicalyieldstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissue',
            name='detail_fetched',
            field=models.BooleanField(db_index=True, default=False, verbose_name='상세조회완료'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='ki',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='낙인배리어(%)'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='stepdown_barriers',
            field=models.JSONField(blank=True, null=True, verbose_name='스텝다운 배리어'),
        ),
    ]
