# Generated by Django 6.0.7 on 2026-07-22 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalissue_detail_fetched_historicalissue_ki_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadarVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=20, verbose_name='등급')),
                ('week_monday', models.DateField(verbose_name='청약주차(월)')),
                ('eval_date', models.DateField(verbose_name='1차 평가일')),
                ('barrier', models.IntegerField(blank=True, null=True, verbose_name='1차 배리어(%)')),
                ('worst_level', models.FloatField(blank=True, null=True, verbose_name='워스트 레벨(%)')),
                ('met', models.BooleanField(null=True, verbose_name='충족 여부')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radar_verdicts', to='core.product')),
            ],
            options={
                'ordering': ['-eval_date'],
                'constraints': [models.UniqueConstraint(fields=('product',), name='uniq_radar_verdict')],
            },
        ),
    ]
