# Generated by Django 6.0.7 on 2026-07-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_radarverdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='broker_url',
            field=models.TextField(blank=True, default='', verbose_name='증권사 상품페이지 URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='prospectus_url',
            field=models.TextField(blank=True, default='', verbose_name='간이투자설명서 URL'),
        ),
    ]
