# Generated by Django 6.0.7 on 2026-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_product_broker_url_product_prospectus_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=120)),
                ('ref', models.CharField(blank=True, max_length=120, verbose_name='유입 도메인')),
                ('visitor', models.CharField(max_length=16, verbose_name='방문자 해시(ip+ua+일자)')),
                ('is_auth', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['date', 'path'], name='core_pagevi_date_d1ee4d_idx')],
            },
        ),
    ]
