# Generated by Django 6.0.7 on 2026-07-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historicalissue_eval_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='include_no_ki',
            field=models.BooleanField(default=True, verbose_name='노낙인 포함'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='ki_max',
            field=models.IntegerField(blank=True, null=True, verbose_name='낙인 최대'),
        ),
        migrations.AlterField(
            model_name='preset',
            name='ki_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='낙인 최소'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_no_ki',
            field=models.BooleanField(default=False, verbose_name='노낙인 여부'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ki',
            field=models.IntegerField(blank=True, null=True, verbose_name='낙인 배리어(%)'),
        ),
    ]
