# Generated by Django 6.0.7 on 2026-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_product_base_eval_date_product_real_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissue',
            name='radar_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='레이더 점수순위'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='radar_tier',
            field=models.CharField(blank=True, max_length=12, verbose_name='레이더 등급'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='sim_early_1y',
            field=models.FloatField(blank=True, null=True, verbose_name='시뮬 1년내 조기상환(%)'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='sim_loss_prob',
            field=models.FloatField(blank=True, null=True, verbose_name='시뮬 손실확률(%)'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='sim_skip',
            field=models.CharField(blank=True, max_length=40, verbose_name='시뮬 불가 사유'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='verdict_level',
            field=models.FloatField(blank=True, null=True, verbose_name='1차 평가일 워스트 레벨(%)'),
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='verdict_met',
            field=models.BooleanField(null=True, verbose_name='1차 조기상환 충족'),
        ),
    ]
