# Generated by Django 6.0.7 on 2026-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_product_eval_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadsReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_id', models.CharField(max_length=64, unique=True, verbose_name='댓글 id')),
                ('post_id', models.CharField(db_index=True, max_length=64, verbose_name='원 게시물 id')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='작성자')),
                ('text', models.TextField(blank=True, verbose_name='본문')),
                ('timestamp', models.DateTimeField(blank=True, null=True, verbose_name='댓글 작성 시각')),
                ('permalink', models.URLField(blank=True, max_length=300, verbose_name='댓글 링크')),
                ('bucket', models.CharField(choices=[('A', 'A 정형응답 가능'), ('B', 'B 사람 답변'), ('C', 'C 개별판단 금지')], db_index=True, max_length=1, verbose_name='버킷')),
                ('bucket_reason', models.CharField(blank=True, max_length=120, verbose_name='분류 근거')),
                ('status', models.CharField(choices=[('new', '수집됨'), ('replied', '자동응답 완료'), ('skipped', '발송 안 함'), ('notified', '알림 발송')], db_index=True, default='new', max_length=10, verbose_name='상태')),
                ('replied_text', models.TextField(blank=True, verbose_name='발송한 문구')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status', 'bucket'], name='core_thread_status_dcfa78_idx')],
            },
        ),
    ]
