# Generated by Django 6.0.7 on 2026-08-04 16:10

import datetime
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_threadsreply'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(models.F('issuer'), models.F('product_no'), django.db.models.functions.comparison.Coalesce('sub_end', models.Value(datetime.date(1, 1, 1))), name='uniq_product'),
        ),
    ]
