# Generated by Django 6.0.7 on 2026-08-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_product_uniq_product_product_uniq_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=24, verbose_name='티커')),
                ('date', models.DateField(verbose_name='거래일')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='시가')),
                ('high', models.FloatField(blank=True, null=True, verbose_name='고가')),
                ('low', models.FloatField(blank=True, null=True, verbose_name='저가')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='종가(미조정)')),
                ('adj_close', models.FloatField(blank=True, null=True, verbose_name='조정종가')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='거래량')),
                ('source', models.CharField(choices=[('원본', '원본 계열 그대로'), ('보완', '대체 계열로 메움')], default='원본', max_length=8, verbose_name='출처')),
                ('source_ticker', models.CharField(blank=True, max_length=24, verbose_name='보완 원본 티커')),
                ('scale', models.FloatField(blank=True, null=True, verbose_name='보완 스케일 계수')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '기초자산 일별 시세',
                'ordering': ['ticker', 'date'],
                'indexes': [models.Index(fields=['date'], name='pricebar_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticker', 'date'), name='uniq_pricebar')],
            },
        ),
    ]
