# Generated by Django 6.0.7 on 2026-08-06 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_pricebar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked_on', models.DateField(db_index=True, verbose_name='질문일(KST)')),
                ('question', models.TextField(verbose_name='질문')),
                ('question_key', models.CharField(db_index=True, max_length=32, verbose_name='질문키')),
                ('status', models.CharField(choices=[('ok', '정상'), ('refused', '거절'), ('guarded', '검사탈락'), ('error', '오류'), ('blocked', '차단')], default='ok', max_length=10, verbose_name='상태')),
                ('refuse_code', models.CharField(blank=True, max_length=20, verbose_name='거절 사유코드')),
                ('guard_flags', models.JSONField(blank=True, default=list, verbose_name='사후검사 위반')),
                ('answer', models.TextField(blank=True, verbose_name='답변 문장')),
                ('tools_used', models.JSONField(blank=True, default=list, verbose_name='실행 도구')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='렌더 컨텍스트')),
                ('input_tokens', models.IntegerField(default=0, verbose_name='입력 토큰')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='출력 토큰')),
                ('cache_write_tokens', models.IntegerField(default=0, verbose_name='캐시 쓰기 토큰')),
                ('cache_read_tokens', models.IntegerField(default=0, verbose_name='캐시 읽기 토큰')),
                ('cost_usd', models.FloatField(default=0.0, verbose_name='추정 비용(USD)')),
                ('usage', models.JSONField(blank=True, default=dict, verbose_name='모델별 사용량')),
                ('elapsed_ms', models.IntegerField(default=0, verbose_name='소요(ms)')),
                ('billed', models.BooleanField(db_index=True, default=False, verbose_name='한도 차감')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ask_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 분석 질문 기록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'asked_on'], name='asklog_user_day_idx'), models.Index(fields=['user', 'asked_on', 'question_key'], name='asklog_cache_idx')],
            },
        ),
    ]
