# Generated by Django 6.0.7 on 2026-08-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_asklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionverdict',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최근 알림'),
        ),
        migrations.AddField(
            model_name='redemptionverdict',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최초 알림'),
        ),
    ]
