# Generated by Django 6.0.7 on 2026-08-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_redemptionverdict_notify_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemptionverdict',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='판정 무시'),
        ),
    ]
