# Generated by Django 6.0.7 on 2026-08-13 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_redemptionverdict_dismissed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='의견')),
                ('contact', models.CharField(blank=True, max_length=120, verbose_name='연락받을 곳(선택)')),
                ('interview_ok', models.BooleanField(default=False, verbose_name='30분 통화 가능')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '베타 피드백',
                'verbose_name_plural': '베타 피드백',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackBannerDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, verbose_name='닫은 시각')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_banner_dismissal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '피드백 배너 닫음',
                'verbose_name_plural': '피드백 배너 닫음',
            },
        ),
    ]
