"""
Django settings for els_platform project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── .env 로드 (BASE_DIR/.env — git에 커밋 안 됨) ──────────────
def _load_dotenv(path):
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())


_load_dotenv(BASE_DIR / ".env")


# SECURITY: 배포 시 반드시 환경변수 DJANGO_SECRET_KEY 설정.
# 미설정이면 아래 임시 키로 폴백하되, 운영 모드에서는 기동을 막는다(하단 참조).
_INSECURE_SECRET_KEY = "django-insecure-dev-only-CHANGE-ME-in-production"
# .env 에 "DJANGO_SECRET_KEY=" 처럼 빈 값이 남아 있는 경우도 미설정으로 본다.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip() or _INSECURE_SECRET_KEY

# 환경변수 DJANGO_DEBUG=1 이면 개발 모드. 기본값은 False(운영).
# 왜 기본이 False인가: 예전 기본값은 True였다. 환경변수가 빠진 채로 뜨면
# 오류 화면에 스택트레이스·로컬 변수·서버 경로·settings 값이 그대로 실려
# 익명 방문자에게 나간다. 설정을 빠뜨린 대가가 너무 크므로 명시적으로
# 켤 때만 켜지게 한다.
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# 운영에서 임시 키를 쓰면 세션·비밀번호 재설정 토큰·CSRF 토큰이 전부 공개된
# 값으로 서명된다(누구나 위조 가능). 조용히 뜨는 것보다 못 뜨는 게 낫다.
if not DEBUG and SECRET_KEY == _INSECURE_SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY가 설정되지 않았습니다. "
        "운영 모드(DEBUG=False)에서는 임시 키로 기동할 수 없습니다.\n"
        "  - 운영: .env 에 DJANGO_SECRET_KEY=<실제 키> 를 넣으세요.\n"
        "  - 로컬 개발: .env 에 DJANGO_DEBUG=1 을 넣거나 키를 만들어 넣으세요.\n"
        '  - 키 생성: python -c "from django.core.management.utils import '
        'get_random_secret_key; print(get_random_secret_key())"'
    )

# 콤마 구분: "els.example.com,192.168.0.10"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

# 터널/역방향 프록시 뒤에서 CSRF 신뢰 도메인 (https 포함)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED", "").split(",") if o.strip()]

# 로그인 성공이 CSRF 토큰을 회전시킨 뒤 중복 제출이 403으로 떨어지는 문제 대응:
# 이미 인증된 사용자는 에러 대신 홈으로 보낸다 (2026-07-31 태훈 계정 사례)
CSRF_FAILURE_VIEW = "core.views.csrf_failure"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # /sitemap.xml 렌더용. django.contrib.sites는 쓰지 않는다 — 사이트맵 뷰가
    # RequestSite(요청 Host)로 폴백하므로 로컬·EC2가 각자 제 도메인을 낸다.
    # ⚠ allauth를 붙이면서도 이 원칙을 지켰다. allauth는 sites 없이도 돌고
    #   (allauth.app_settings.SITES_ENABLED = apps.is_installed("django.contrib.sites")),
    #   소셜 앱 키를 DB(SocialApp)가 아니라 SOCIALACCOUNT_PROVIDERS 설정으로
    #   주입하면 sites가 아예 필요 없다. sites를 넣었다면 sitemap 뷰의
    #   get_current_site()가 Site 테이블을 보게 되어 도메인이 example.com으로
    #   나가거나 Site.DoesNotExist로 사이트맵이 깨졌을 것이다.
    'django.contrib.sitemaps',
    'core',
    # ── 소셜 로그인 ──
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.kakao',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.naver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',   # allauth 필수 (auth 뒤)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.PageViewMiddleware',   # 자체 접속 집계 (맨 뒤: user 확정 후)
]

ROOT_URLCONF = 'els_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.seo',
                'core.context_processors.social',
            ],
        },
    },
]

WSGI_APPLICATION = 'els_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # SQLite 기본값은 잠금을 만나면 즉시 실패한다. 새벽 배치가 도는 동안
        # 수동 작업(백필·수집)이 겹치면 'database is locked'로 배치가 죽는다
        # (2026-08-03 update_prices 실패). 최대 30초 대기 후 재시도한다.
        'OPTIONS': {
            'timeout': 30,
            # WAL: 읽기와 쓰기가 서로를 막지 않게 한다 (웹 요청 ↔ 배치 동시성)
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
            # 위 둘만으로는 부족했다. SQLite는 트랜잭션을 읽기로 시작했다가
            # 쓰기로 승격할 때 그 사이 다른 연결이 쓰면, 교착을 피하려고
            # busy_timeout을 무시하고 즉시 SQLITE_BUSY를 낸다. 그래서 30초를
            # 기다리지 않고 7초 만에 죽었다.
            # (2026-08-03 09:31 update_prices — 같은 시각 로그인 요청이 세션을
            #  기록하면서 충돌. 배치 시각 09:30이 아침 접속과 겹친다.)
            # IMMEDIATE는 트랜잭션 시작 시점에 쓰기 잠금을 먼저 잡는다. 이 경로는
            # busy_timeout이 정상 적용되므로 최대 30초 대기 후 진행한다.
            'transaction_mode': 'IMMEDIATE',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── 보안 (운영 모드에서만 강제) ──────────────────
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ── ELS 레이더 설정 ──────────────────────────────
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/weekly/'   # 로그인 직후엔 주간청약 (홈 /는 항상 랜딩)
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ── 소셜 로그인 (django-allauth) ─────────────────────────────
# 카카오부터. 네이버·구글은 아래 SOCIAL_PROVIDERS 표에 한 줄 더 넣고
# INSTALLED_APPS에 provider 앱을 추가하면 화면·URL이 함께 따라온다.
#
# 키는 .env에만 둔다. 코드·문서·저장소에 실제 값을 적지 않는다.
# 키가 비어 있으면 SOCIAL_LOGIN_ENABLED가 False가 되고, 화면에서 버튼이
# 사라지며 /accounts/kakao/login/ 도 로그인 화면으로 되돌린다
# (core.views.kakao_login_entry). 눌러서 에러 페이지를 보는 일이 없게 한다.
KAKAO_CLIENT_ID = os.environ.get("KAKAO_CLIENT_ID", "").strip()
KAKAO_SECRET = os.environ.get("KAKAO_SECRET", "").strip()
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "").strip()
GOOGLE_SECRET = os.environ.get("GOOGLE_SECRET", "").strip()
NAVER_CLIENT_ID = os.environ.get("NAVER_CLIENT_ID", "").strip()
NAVER_SECRET = os.environ.get("NAVER_SECRET", "").strip()

# 화면·URL 가드가 함께 보는 스위치. 3사 확장 시 여기에 항목이 늘어난다.
#   provider_id: (사람이 읽는 이름, 키가 채워졌는가)
SOCIAL_PROVIDERS = {
    "kakao": {"label": "카카오", "enabled": bool(KAKAO_CLIENT_ID)},
    "google": {"label": "구글", "enabled": bool(GOOGLE_CLIENT_ID)},
    "naver": {"label": "네이버", "enabled": bool(NAVER_CLIENT_ID)},
}
SOCIAL_LOGIN_ENABLED = any(p["enabled"] for p in SOCIAL_PROVIDERS.values())

AUTHENTICATION_BACKENDS = [
    # 기존 5개 계정의 아이디·비밀번호 로그인. 순서상 먼저 시도된다.
    'django.contrib.auth.backends.ModelBackend',
    # 소셜 로그인 세션 수립용
    'allauth.account.auth_backends.AuthenticationBackend',
]

# 우리 로그인·가입 화면을 그대로 쓴다. allauth의 account 화면은 URL에 붙이지
# 않으므로 아래 값들은 소셜 흐름이 참조하는 최소 설정이다.
ACCOUNT_LOGIN_METHODS = {"username"}
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
# 이메일 인증 메일은 보내지 않는다 — 기존 가입 절차와 같게 둔다.
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_UNIQUE_EMAIL = True

SOCIALACCOUNT_ADAPTER = "core.socialauth.ELSSocialAccountAdapter"
# GET 한 번으로 로그인이 시작되지 않게 한다(CSRF·낚시 방지). 버튼은 POST 폼이다.
SOCIALACCOUNT_LOGIN_ON_GET = False
# 액세스 토큰을 DB에 남기지 않는다. 우리는 프로필을 한 번 읽고 끝이라
# 보관할 이유가 없고, 남기면 유출 시 피해만 커진다.
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_QUERY_EMAIL = True
# 카카오는 사용자가 이메일 제공에 동의하지 않을 수 있다. 이메일을 필수로 걸면
# 그 사용자는 가입 자체가 막힌다 — 받지 못하면 못 받은 대로 가입시킨다.
SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_AUTO_SIGNUP = True

# ⚠ 자동 연결의 핵심 두 줄 ─────────────────────────────────
# EMAIL_AUTHENTICATION: 소셜에서 온 **검증된** 이메일이 기존 로컬 계정의
#   이메일과 같으면 그 계정으로 로그인시킨다. allauth는 verified=True인
#   주소만 대조한다(socialaccount/adapter.py authenticate_by_email:
#   `[e.email for e in sociallogin.email_addresses if e.verified]`).
#   카카오 provider는 kakao_account.is_email_verified 를 그대로 verified에
#   싣는다(providers/kakao/provider.py extract_email_addresses).
#   → 검증 안 된 이메일은 이 경로를 아예 타지 못한다.
# ⚠ 전역(SOCIALACCOUNT_EMAIL_AUTHENTICATION)이 아니라 **provider별**로 켠다.
#   공식 문서가 "fully trusted 한 provider에만 켜라"고 못 박고 있어서,
#   네이버·구글을 붙일 때 그때마다 다시 판단하도록 강제한다.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = False
# AUTO_CONNECT: 위 대조로 로그인한 뒤 소셜 계정을 그 로컬 계정에 실제로
#   붙여 둔다. 붙여두지 않으면 나중에 이메일을 바꾸는 순간 소셜 로그인이
#   끊긴다. 이 설정은 provider별 지정이 없어 전역으로만 켤 수 있다.
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    "kakao": {
        # DB(SocialApp)가 아니라 설정으로 키를 준다 — django.contrib.sites를
        # 안 쓰기 위한 선택이자, 키를 .env 한 곳에서만 관리하기 위한 선택이다.
        # 키가 비어 있으면 APPS를 아예 넣지 않는다(설정에 빈 앱이 남아 있으면
        # allauth가 그 앱으로 인증을 시도하다 500을 낸다).
        **({"APPS": [{
            "client_id": KAKAO_CLIENT_ID,
            "secret": KAKAO_SECRET,
            "key": "",
        }]} if KAKAO_CLIENT_ID else {}),
        # 카카오 개발자센터 '동의항목'에서 켠 것만 실제로 온다.
        "SCOPE": ["account_email", "profile_nickname"],
        # 이 provider만 이메일 대조 로그인을 허용한다 (위 주석 참조).
        "EMAIL_AUTHENTICATION": True,
    },
    "google": {
        **({"APPS": [{
            "client_id": GOOGLE_CLIENT_ID,
            "secret": GOOGLE_SECRET,
            "key": "",
        }]} if GOOGLE_CLIENT_ID else {}),
        "SCOPE": ["profile", "email"],
        # 구글은 스스로 이메일 소유를 확인한 계정만 내려주므로(카카오처럼
        # 사용자 설정에 따라 안 온 채 통과하는 경우가 없다) 신뢰하고 켠다.
        "EMAIL_AUTHENTICATION": True,
    },
    "naver": {
        **({"APPS": [{
            "client_id": NAVER_CLIENT_ID,
            "secret": NAVER_SECRET,
            "key": "",
        }]} if NAVER_CLIENT_ID else {}),
        # 네이버는 OAuth 요청에 scope를 안 싣는다 — 무엇을 내려줄지는
        # 네이버 개발자센터 '제공정보' 설정이 서버 쪽에서 결정한다.
        # allauth 쪽도 이메일이 오면 항상 verified=True로 싣는다(같은 이유로 신뢰).
        "EMAIL_AUTHENTICATION": True,
    },
}

# ELS_Curator exe가 엑셀을 생성하는 폴더 (환경변수로 덮어쓰기 가능).
# 프로젝트 폴더 바로 위의 downloads/를 가리킨다. 절대경로를 박아두면 폴더를
# 옮길 때마다 조용히 깨진다 — 2026-08-04에 ELS투자 → claude/ELSradar로
# 옮기면서 실제로 깨졌다.
ELS_DOWNLOADS_DIR = os.environ.get(
    "ELS_DOWNLOADS_DIR", str(BASE_DIR.parent / "downloads"))

# 텔레그램 (BASE_DIR/.env 또는 환경변수에서 로드 — _load_dotenv가 이미 채움)
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")

# 개인 투자 알림(조기상환 판정·평가일 D-7/D-1·낙인 근접)을 받을 계정.
# 텔레그램은 chat_id 하나짜리 공용 채널이라 전 계정 투자가 한 방에 섞여 온다.
# 2026-08-10 조 팀장 지시로 admin 소유 투자만 남긴다.
# 쉼표로 여러 계정을 넣을 수 있다 — 되돌리거나 계정을 추가할 때 .env만 고치면
# 되도록 상수가 아니라 설정으로 뒀다. 빈 값이면 제한하지 않는다(전 계정 발송).
# 집계성 알림(주간 다이제스트·배치 보고·헬스체크)에는 적용되지 않는다.
TELEGRAM_ALERT_USERNAMES = [
    u.strip() for u in os.environ.get("TELEGRAM_ALERT_USERNAMES", "admin").split(",")
    if u.strip()
]

# ── 텔레그램 알림 종류별 킬스위치 ────────────────────────────
# 아래 4종은 2026-08-11 조 팀장 지시로 비활성화했다. 기본값 꺼짐.
# 끄는 것은 **텔레그램 발송뿐**이다. 판정 로직과 DB 기록(RedemptionAlert·
# KnockInAlert·KnockInStatus·NotifiedMatch)은 그대로 돌고, 웹 푸시도 그대로
# 나간다 — 웹 푸시는 계정별 채널이라 공용 텔레그램과 별개다(core/notify.py 주석).
# 코드를 지우지 않고 조건 분기로만 막았으므로, 다시 켜려면 .env에
# 해당 이름을 1로 넣고 재기동하면 된다(배포 불필요).
#
# 보유 투자 평가일 D-1 임박 — core/notify.py notify_redemptions
TELEGRAM_REDEMPTION_ALERT_ENABLED = os.environ.get(
    "TELEGRAM_REDEMPTION_ALERT_ENABLED", "0") == "1"
# 낙인 근접 경보(위험·경고) — core/management/commands/update_prices.py _maybe_alert
TELEGRAM_KNOCKIN_ALERT_ENABLED = os.environ.get(
    "TELEGRAM_KNOCKIN_ALERT_ENABLED", "0") == "1"
# 신규 프리셋 매칭 상품 — core/notify.py notify_preset_matches
TELEGRAM_PRESET_MATCH_ALERT_ENABLED = os.environ.get(
    "TELEGRAM_PRESET_MATCH_ALERT_ENABLED", "0") == "1"
# 관심상품 청약마감 D-1(가족 공용) — core/notify.py notify_watchlist_deadline
# 계정별 웹 푸시는 이 설정과 무관하게 그대로 나간다.
TELEGRAM_WATCHLIST_DEADLINE_ALERT_ENABLED = os.environ.get(
    "TELEGRAM_WATCHLIST_DEADLINE_ALERT_ENABLED", "0") == "1"

# 베타 피드백 접수 — core/views.py _feedback_notify
# ⚠ 위 4종과 달리 **기본값 켜짐**이다. 위 넷은 매일 반복되는 투자 알림이라
#   꺼도 화면에서 다시 볼 수 있지만, 피드백은 사용자가 한 번 쓰고 마는 것이라
#   알림을 놓치면 회신 타이밍(커피 기프티콘 발송)을 통째로 놓친다.
#   기록은 DB(Feedback)에 남으므로 꺼도 유실되지는 않는다 — 관리자 화면에서 본다.
# ⚠ TELEGRAM_ALERT_USERNAMES(개인 투자 알림 대상 제한)를 적용하지 않는다.
#   그건 '누구의 투자를 공용 채널에 올릴까'의 문제고, 피드백은 어느 계정이
#   보냈든 운영자가 받아야 하는 접수 알림이다.
TELEGRAM_FEEDBACK_ALERT_ENABLED = os.environ.get(
    "TELEGRAM_FEEDBACK_ALERT_ENABLED", "1") == "1"

# 웹 푸시 (VAPID — .env에 키 보관, 로컬/EC2 동일 키. 미설정 시 푸시 발송·버튼 비활성)
VAPID_PUBLIC_KEY = os.environ.get("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.environ.get("VAPID_PRIVATE_KEY", "")
VAPID_SUB = os.environ.get("VAPID_SUB", "mailto:lifedd1984@gmail.com")

# AI 리서치 (Claude Haiku — 자연어 → 검색 필터 변환 전용)
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

# ── 구글 시트 동기화 (/portfolio/sync.json) ──────────────────
# 조 팀장 'ELS투자 리스트' 시트가 하루 한 번 읽어 가는 피드. 서버가 시트에
# 쓰는 게 아니라 시트가 우리를 읽는다 — 구글 자격증명을 서버에 두지 않기 위함.
#
# 토큰이 이 엔드포인트의 유일한 자물쇠다(로그인 세션을 못 쓴다. Apps Script는
# 쿠키를 들고 다니지 못한다). 그래서 기본값이 빈 값이고, 빈 값이면 엔드포인트
# 자체가 404다 — 설정을 빠뜨린 채 배포해도 포트폴리오가 열리지 않는다.
# 값은 .env 에만 둔다. 코드·문서·저장소에 실제 토큰을 적지 않는다.
#   생성 예: python -c "import secrets; print(secrets.token_urlsafe(32))"
SHEET_SYNC_TOKEN = os.environ.get("SHEET_SYNC_TOKEN", "").strip()

# 시트로 내보낼 포트폴리오의 주인 계정 하나. 운영 DB는 admin이 보유분을 갖고
# 있다. 상수로 박지 않는 이유는 로컬 개발 DB의 소유 계정 이름이 다르기
# 때문이다(로컬은 taehoon) — 계정이 바뀌어도 .env만 고치면 되게 둔다.
SHEET_SYNC_USERNAME = os.environ.get("SHEET_SYNC_USERNAME", "admin").strip()

# ── AI 분석 질문 (/ask/) ────────────────────────────
# 2턴 구조: 해석(질문 → 도구 호출)은 Haiku, 설명(도구 결과 → 문장)은 Sonnet.
# 해석은 스키마 채우기라 값싼 모델로 충분하고, 설명은 사용자가 읽는 문장이라
# 품질이 그대로 드러난다. 모델을 바꾸면 캐시가 통째로 무효화되니 주의.
ASK_MODEL_INTERPRET = os.environ.get("ASK_MODEL_INTERPRET", "claude-haiku-4-5")
ASK_MODEL_ANSWER = os.environ.get("ASK_MODEL_ANSWER", "claude-sonnet-5")
PORTFOLIO_AI_ENABLED = os.environ.get("PORTFOLIO_AI_ENABLED", "1") == "1"

# 포트폴리오 유형 배분 가이드 — 보유 현황에 종목형/지수형 비율 막대 + 권장 대비 편차.
# 권장 종목형 70은 10년 배분 시뮬 근거(2026-09-03). 노출·수치는 환경변수로 조정.
ALLOC_GUIDE_ENABLED = os.environ.get("ALLOC_GUIDE_ENABLED", "1") == "1"
ALLOC_GUIDE_STOCK_RATIO = int(os.environ.get("ALLOC_GUIDE_STOCK_RATIO", "70"))
ALLOC_GUIDE_TOLERANCE = int(os.environ.get("ALLOC_GUIDE_TOLERANCE", "10"))

# 출력 상한. 해석턴은 도구 호출 하나면 되고, 설명턴은 3~5문장 + 후속질문이다.
# ⚠ Sonnet 5는 thinking 파라미터를 생략하면 adaptive가 켜지고, max_tokens는
#   thinking+본문 합계 상한이다. ask_agent가 thinking을 명시적으로 끈다.
ASK_MAX_TOKENS = {"interpret": 700, "answer": 900}

# 킬스위치. 사고가 나면 배포 없이 환경변수로 끈다.
ASK_ENABLED = os.environ.get("ASK_ENABLED", "1") != "0"

# 서비스 전체 하루 상한. 1인 한도는 계정을 여러 개 만들면 우회되므로
# 마지막 방어선을 하나 더 둔다. 넘으면 아무도 새 질문을 못 한다(캐시 재열람은 가능).
ASK_GLOBAL_DAILY_CAP = int(os.environ.get("ASK_GLOBAL_DAILY_CAP", "200"))

# 1인 하루 한도. 값이 None이면 무제한.
# 권한 구분: is_staff = '가족'(엑셀 업로드 권한을 가진 일반 회원),
#            is_superuser = 운영자. 가족은 서비스 사용자지 운영자가 아니므로
#            일반과 같은 한도를 준다 (운영 DB 기준 해당 계정 1명).
#            무제한을 넓게 열면 비용이 예측 밖으로 나간다.
ASK_DAILY_LIMITS = {
    "default": 3,
    "staff": 3,
    "superuser": None,
}

# 질문 길이 상한 (초과분은 잘라서 보낸다 — 프롬프트 폭주 방지)
ASK_MAX_QUESTION_CHARS = 300

# 알림 메시지에 넣을 사이트 주소 (배포 시 실제 도메인으로)
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")

# ── 이메일 (비밀번호 재설정용) ──
# .env에 EMAIL_HOST_USER / EMAIL_HOST_PASSWORD(구글 앱 비밀번호) 설정 시 실제 발송.
# 미설정이면 콘솔 출력(개발용)으로 폴백.
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# 업로드 엑셀 임시 저장 폴더
UPLOAD_DIR = BASE_DIR / "uploads"

# ── 로깅 ─────────────────────────────────────────────────
# 왜 필요한가
#   기본값은 django.request 에러를 mail_admins로만 보내는데 ADMINS가 비어 있어
#   그대로 버려진다. 2026-08-03에 /weekly/가 비로그인 방문자 전원에게 500을
#   내며 10시간 죽어 있었는데, 저널에는 상태코드 500만 남고 트레이스백이
#   어디에도 없어서 아무도 몰랐다. 실사용자 60명이 그 화면을 봤다.
# 파일로 남기고, 500은 텔레그램으로도 즉시 올린다.
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "full": {"format": "[{asctime}] {levelname} {name} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "full"},
        "errfile": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "django_error.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "full",
            "encoding": "utf-8",
        },
        # 500만 텔레그램으로. 4xx까지 보내면 크롤러 때문에 알림이 무의미해진다.
        "telegram": {
            "class": "core.logging_telegram.TelegramErrorHandler",
            "level": "ERROR",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["errfile", "console", "telegram"],
            "level": "ERROR",
            "propagate": False,
        },
        "core": {"handlers": ["errfile", "console"], "level": "INFO", "propagate": False},
    },
}

# ── 테스트 실행 시에만 적용되는 가속 설정 ──────────────────────────
# 운영 동작에는 영향이 없다. manage.py test 로 돌 때만 켜진다.
#   · 비밀번호 해싱: 기본 PBKDF2는 의도적으로 느리다(보안). 테스트가
#     사용자를 20번 만드는데 그때마다 수백 ms를 태울 이유가 없다.
#   · 마이그레이션: 테스트 DB는 매번 27개를 순서대로 적용한다. 모델에서
#     직접 만들면 그 시간이 통째로 빠진다.
# (2026-08-09 — 전체 테스트가 6분을 넘겨 정리)
if "test" in sys.argv:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]
    LOGGING["loggers"]["core"]["level"] = "CRITICAL"
    PORTFOLIO_AI_ENABLED = False
