"""
Django settings for els_platform project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── .env 로드 (BASE_DIR/.env — git에 커밋 안 됨) ──────────────
def _load_dotenv(path):
    if not os.path.exists(path):
        return
    with open(path, encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())


_load_dotenv(BASE_DIR / ".env")


# SECURITY: 배포 시 반드시 환경변수 DJANGO_SECRET_KEY 설정.
# 미설정이면 아래 임시 키로 폴백하되, 운영 모드에서는 기동을 막는다(하단 참조).
_INSECURE_SECRET_KEY = "django-insecure-dev-only-CHANGE-ME-in-production"
# .env 에 "DJANGO_SECRET_KEY=" 처럼 빈 값이 남아 있는 경우도 미설정으로 본다.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip() or _INSECURE_SECRET_KEY

# 환경변수 DJANGO_DEBUG=1 이면 개발 모드. 기본값은 False(운영).
# 왜 기본이 False인가: 예전 기본값은 True였다. 환경변수가 빠진 채로 뜨면
# 오류 화면에 스택트레이스·로컬 변수·서버 경로·settings 값이 그대로 실려
# 익명 방문자에게 나간다. 설정을 빠뜨린 대가가 너무 크므로 명시적으로
# 켤 때만 켜지게 한다.
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# 운영에서 임시 키를 쓰면 세션·비밀번호 재설정 토큰·CSRF 토큰이 전부 공개된
# 값으로 서명된다(누구나 위조 가능). 조용히 뜨는 것보다 못 뜨는 게 낫다.
if not DEBUG and SECRET_KEY == _INSECURE_SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY가 설정되지 않았습니다. "
        "운영 모드(DEBUG=False)에서는 임시 키로 기동할 수 없습니다.\n"
        "  - 운영: .env 에 DJANGO_SECRET_KEY=<실제 키> 를 넣으세요.\n"
        "  - 로컬 개발: .env 에 DJANGO_DEBUG=1 을 넣거나 키를 만들어 넣으세요.\n"
        '  - 키 생성: python -c "from django.core.management.utils import '
        'get_random_secret_key; print(get_random_secret_key())"'
    )

# 콤마 구분: "els.example.com,192.168.0.10"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]

# 터널/역방향 프록시 뒤에서 CSRF 신뢰 도메인 (https 포함)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED", "").split(",") if o.strip()]

# 로그인 성공이 CSRF 토큰을 회전시킨 뒤 중복 제출이 403으로 떨어지는 문제 대응:
# 이미 인증된 사용자는 에러 대신 홈으로 보낸다 (2026-07-31 태훈 계정 사례)
CSRF_FAILURE_VIEW = "core.views.csrf_failure"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.PageViewMiddleware',   # 자체 접속 집계 (맨 뒤: user 확정 후)
]

ROOT_URLCONF = 'els_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'els_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # SQLite 기본값은 잠금을 만나면 즉시 실패한다. 새벽 배치가 도는 동안
        # 수동 작업(백필·수집)이 겹치면 'database is locked'로 배치가 죽는다
        # (2026-08-03 update_prices 실패). 최대 30초 대기 후 재시도한다.
        'OPTIONS': {
            'timeout': 30,
            # WAL: 읽기와 쓰기가 서로를 막지 않게 한다 (웹 요청 ↔ 배치 동시성)
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
            # 위 둘만으로는 부족했다. SQLite는 트랜잭션을 읽기로 시작했다가
            # 쓰기로 승격할 때 그 사이 다른 연결이 쓰면, 교착을 피하려고
            # busy_timeout을 무시하고 즉시 SQLITE_BUSY를 낸다. 그래서 30초를
            # 기다리지 않고 7초 만에 죽었다.
            # (2026-08-03 09:31 update_prices — 같은 시각 로그인 요청이 세션을
            #  기록하면서 충돌. 배치 시각 09:30이 아침 접속과 겹친다.)
            # IMMEDIATE는 트랜잭션 시작 시점에 쓰기 잠금을 먼저 잡는다. 이 경로는
            # busy_timeout이 정상 적용되므로 최대 30초 대기 후 진행한다.
            'transaction_mode': 'IMMEDIATE',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── 보안 (운영 모드에서만 강제) ──────────────────
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ── ELS 레이더 설정 ──────────────────────────────
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/weekly/'   # 로그인 직후엔 주간청약 (홈 /는 항상 랜딩)
LOGOUT_REDIRECT_URL = '/accounts/login/'

# ELS_Curator exe가 엑셀을 생성하는 폴더 (환경변수로 덮어쓰기 가능).
# 프로젝트 폴더 바로 위의 downloads/를 가리킨다. 절대경로를 박아두면 폴더를
# 옮길 때마다 조용히 깨진다 — 2026-08-04에 ELS투자 → claude/ELSradar로
# 옮기면서 실제로 깨졌다.
ELS_DOWNLOADS_DIR = os.environ.get(
    "ELS_DOWNLOADS_DIR", str(BASE_DIR.parent / "downloads"))

# 텔레그램 (BASE_DIR/.env 또는 환경변수에서 로드 — _load_dotenv가 이미 채움)
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_CHAT_ID = os.environ.get("TELEGRAM_CHAT_ID", "")

# 웹 푸시 (VAPID — .env에 키 보관, 로컬/EC2 동일 키. 미설정 시 푸시 발송·버튼 비활성)
VAPID_PUBLIC_KEY = os.environ.get("VAPID_PUBLIC_KEY", "")
VAPID_PRIVATE_KEY = os.environ.get("VAPID_PRIVATE_KEY", "")
VAPID_SUB = os.environ.get("VAPID_SUB", "mailto:lifedd1984@gmail.com")

# AI 리서치 (Claude Haiku — 자연어 → 검색 필터 변환 전용)
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")

# 알림 메시지에 넣을 사이트 주소 (배포 시 실제 도메인으로)
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")

# ── 이메일 (비밀번호 재설정용) ──
# .env에 EMAIL_HOST_USER / EMAIL_HOST_PASSWORD(구글 앱 비밀번호) 설정 시 실제 발송.
# 미설정이면 콘솔 출력(개발용)으로 폴백.
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = "smtp.gmail.com"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# 업로드 엑셀 임시 저장 폴더
UPLOAD_DIR = BASE_DIR / "uploads"

# ── 로깅 ─────────────────────────────────────────────────
# 왜 필요한가
#   기본값은 django.request 에러를 mail_admins로만 보내는데 ADMINS가 비어 있어
#   그대로 버려진다. 2026-08-03에 /weekly/가 비로그인 방문자 전원에게 500을
#   내며 10시간 죽어 있었는데, 저널에는 상태코드 500만 남고 트레이스백이
#   어디에도 없어서 아무도 몰랐다. 실사용자 60명이 그 화면을 봤다.
# 파일로 남기고, 500은 텔레그램으로도 즉시 올린다.
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "full": {"format": "[{asctime}] {levelname} {name} {message}", "style": "{"},
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "full"},
        "errfile": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOG_DIR / "django_error.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 5,
            "formatter": "full",
            "encoding": "utf-8",
        },
        # 500만 텔레그램으로. 4xx까지 보내면 크롤러 때문에 알림이 무의미해진다.
        "telegram": {
            "class": "core.logging_telegram.TelegramErrorHandler",
            "level": "ERROR",
        },
    },
    "loggers": {
        "django.request": {
            "handlers": ["errfile", "console", "telegram"],
            "level": "ERROR",
            "propagate": False,
        },
        "core": {"handlers": ["errfile", "console"], "level": "INFO", "propagate": False},
    },
}
